name:                pixel-printer
version:             0.1.0.0
github:              "githubuser/pixel-printer"
license:             BSD3
author:              "Zachary Sarver"
maintainer:          "Zachary.Sarver@gmail.com"
copyright:           "2021 Zachary Sarver"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/pixel-printer#readme>

dependencies:
- base >= 4.7 && < 5
- JuicyPixels >= 3.3 && < 3.4
- lens >= 4.19 && < 5

library:
  source-dirs: src

executables:
  pixel-printer-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pixel-printer

tests:
  pixel-printer-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pixel-printer
